---
title: "Assignement 1"
author: "Givaldo R00182595"
date: "11/03/2020"
---



```{r setup, include=FALSE}

# install.packages("readxl")
# install.packages("tidyverse")
# install.packages("ggplot2")

library(maps)
library(readr)
library(readxl)
library(readr)
require(data.table)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(gganimate)
library(dplyr)
library(reshape2)
library(ggthemes)
library(gifski)
library(av)


```


```{r }


my.path =""
my.path <- dirname(rstudioapi::getActiveDocumentContext()$path)

setwd(my.path)


# 
# setwd("E:\\Givaldo\\DATA SCIENCE\\MESTRADO CIT\\SUBJECTS\\Second Semester\\Visualizatin and Analytics\\Project 1")

Indicators <- read.csv("Indicators.csv")

Country <- read.csv("Country.csv")

Country_Region <-Country[,c(1,8)]
unique(na.omit(Country_Region$Region))

Indicators2 <- merge(Indicators,Country_Region, by=c("CountryCode","CountryCode"))

# colnames(Indicators2)
# Country$ShortName

CountryNam <- unique(Indicators2[,c(1)])
IndicatorNam <- unique(Indicators2[,c(3)])
IndicatorCod <- unique(Indicators2[,c(4)])
region <- unique(Indicators2[,c(7)])


Indicators_europe <- Indicators2 %>%
  filter(Region=="Europe & Central Asia")


wide_format <- Indicators_europe[,-c(3)] %>% 
  spread(key = "IndicatorCode",        # Name of new key column
         value = "Value") # Name of column for values


Indicators_europe2 <- Indicators_europe %>%
        filter(IndicatorName=="GDP (current LCU)" |
                IndicatorName=="Life expectancy at birth, total (years)"| 
                IndicatorName=="International migrant stock, total"|
                IndicatorName=="Population, total"
                 )
        
# str(Indicators_europe2)
# colnames(Indicators_europe2)
# 

wide_format <- Indicators_europe2[,-c(4)] %>% 
  spread(key = "IndicatorName",        # Name of new key column
         value = "Value") # Name of column for values

names(wide_format)<-c("CountryCode","CountryName","Year","Region","GDP","migrant","Lifeexpectancy","Population")

#colnames(wide_format[,c(-6)])
wide_format2 <- na.omit(wide_format[,c(-6)])

#colnames(wide_format2)
wide_format2 <- wide_format2[,c(2,4,3,5,6,7)]
#unique(wide_format2$CountryName)
# View(wide_format2)
# 
wide_format3 <- wide_format2 %>%
  filter(  CountryName=="Switzerland"|
           CountryName=="Germany"|
           CountryName=="Spain"|
           CountryName=="Finland"|
           CountryName=="United Kingdom"|
           CountryName=="Greece"|
           CountryName=="Austria"|
           CountryName=="Belgium"|
           CountryName=="Sweden"|
             CountryName=="Poland"|
             CountryName=="France"|
             CountryName=="Ireland"|
             CountryName=="Iceland"|
             CountryName=="Portugal"|
             CountryName=="Italy"|
             CountryName=="Denmark"|
           CountryName=="Norway")


library(ggplot2)
library(gganimate)

# Make a ggplot, but add frame=year: one image per year
ggplot(wide_format3, aes(GDP, 
                         Lifeexpectancy, 
                         size = Population, 
                         color = CountryName)) +
                        geom_point() +
                        scale_x_log10() +
                        theme_bw() +
                        # gganimate specific bits:
                        labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
                        transition_time(Year) +
                        ease_aes('linear')

# Save at gif:
anim_save("Lifeexpectancy.gif")


```

```{r setup, include=FALSE}

Country_Region <-Country[,c(1,8)]
# count(Indicators)
# count(Country_Region)

# Indicators2 <- merge(Indicators,Country_Region, by=c("CountryCode","CountryCode"))

# head(Indicators2)
# count(Indicators2)
# 
# colnames(Indicators2)
# Country$ShortName

CountryNam <- unique(Indicators2[,c(1)])
IndicatorNam <- unique(Indicators2[,c(3)])
IndicatorCod <- unique(Indicators2[,c(4)])
region <- unique(Indicators2[,c(7)])

Indicators_europe <- Indicators2 %>%
  filter(Region=="Europe & Central Asia")

count(Indicators_europe)

# GDP (current LCU)
# GDP per capita growth (annual %)
# Gross capital formation (% of GDP)


Indicators_europe2 <- Indicators_europe %>%
  filter(IndicatorName=="GDP (current LCU)" 
           # IndicatorName=="Life expectancy at birth, total (years)"| 
           # IndicatorName=="International migrant stock, total"|
           # IndicatorName=="Population, total"
  )

count(Indicators_europe2)

str(Indicators_europe2)
colnames(Indicators_europe2)


wide_format <- Indicators_europe2[,-c(4,7)] %>% 
  spread(key = "IndicatorName",        # Name of new key column
         value = "Value") # Name of column for values

# count(wide_format)
# 
# colnames(wide_format)
# View(wide_format)

# names(wide_format)<-c("country_cod","country_name","year","value","migrant","Lifeexpectancy","Population")
names(wide_format)<-c("country_cod","country_name","year","value")

colnames(wide_format[,c(-6)])
# wide_format2 <- na.omit(wide_format[,c(-6)])
# 
# colnames(wide_format2)
# 
# colnames(wide_format2[,c(1,3,4)])
# wide_format2 <- wide_format2[,c(1,3,4)]
# unique(wide_format2$country_name.1)
# View(wide_format2)


# wide_format3 <- wide_format2 %>%
#   filter(  country_name.1=="Switzerland"|
#              country_name.1=="Germany"|
#              country_name.1=="Spain"|
#              country_name.1=="Finland"|
#              country_name.1=="United Kingdom"|
#              country_name.1=="Greece"|
#              country_name.1=="Austria"|
#              country_name.1=="Belgium"|
#              country_name.1=="Sweden"|
#              country_name.1=="Poland"|
#              country_name.1=="France"|
#              country_name.1=="Ireland"|
#              country_name.1=="Iceland"|
#              country_name.1=="Portugal"|
#              country_name.1=="Italy"|
#              country_name.1=="Denmark"|
#              country_name.1=="Norway")

count(wide_format)


#=======================================


getwd()
# setwd("E:\\Givaldo\\DATA SCIENCE\\MESTRADO CIT\\SUBJECTS\\Second Semester\\Visualizatin and Analytics\\Project 1\\animated_bar_charts_in_R-master\\data")
# gdp_tidy <- read_csv("gdp_tidy.csv")
# 
# count(gdp_tidy)

gdp_tidy <-as.data.frame(wide_format)

gdp_formatted <- gdp_tidy %>%
  group_by(year) %>%
  # The * 1 makes it possible to have non-integer ranks while sliding
  mutate(rank = rank(-value),
         Value_rel = value/value[rank==1],
         Value_lbl = paste0(" ",round(value/100000000))) %>%
  group_by(country_name) %>% 
  filter(rank <=10) %>%
  ungroup()

# Animation


anim <- ggplot(gdp_formatted, aes(rank, group = country_name, 
                fill = as.factor(country_name), color = as.factor(country_name))) +
  geom_tile(aes(y = value/2,
                height = value,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(country_name, " ")), vjust = 0.2, hjust = 1) +
  geom_text(aes(y=value,label = Value_lbl, hjust=0)) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
         axis.title.y=element_blank(),
        legend.position="none",
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.grid.major.x = element_line( size=.1, color="grey" ),
        panel.grid.minor.x = element_line( size=.1, color="grey" ),
        plot.title=element_text(size=25, hjust=0.5, face="bold", colour="grey", vjust=-1),
        plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="grey"),
        plot.caption =element_text(size=8, hjust=0.5, face="italic", color="grey"),
        plot.background=element_blank(),
       plot.margin = margin(2,2, 2, 4, "cm")) +
  transition_states(year, transition_length = 4, state_length = 1) +
  view_follow(fixed_x = TRUE)  +
  labs(title = 'GDP (current LCU) per year : {closest_state}',  
       subtitle  =  "Top 10 Europe Countries",
       caption  = "GDP (current LCU) | Data Source: World Bank Data") 

# For GIF
# install.packages("gifski")
library(gifski)

animate(anim, 200, fps = 20,  width = 1200, height = 1000, 
        renderer = gifski_renderer("gganim.gif")) 

```



```{r }



# 
# my.path <- dirname(rstudioapi::getActiveDocumentContext()$path)
# setwd(my.path)
# 
# Indicators <- read.csv("Indicators.csv")
# 
# Country <- read.csv("Country.csv")

Country_Region <-Country[,c(1,8)]
unique(na.omit(Country_Region$Region))

Indicators2 <- merge(Indicators,Country_Region, by=c("CountryCode","CountryCode"))
# colnames(Indicators2)
# Country$ShortName

CountryNam <- unique(Indicators2[,c(1)])
IndicatorNam <- unique(Indicators2[,c(3)])
IndicatorCod <- unique(Indicators2[,c(4)])
region <- unique(Indicators2[,c(7)])


Indicators_europe <- Indicators2 %>%
  filter(Region=="Europe & Central Asia"|
         Region=="South Asia"|
         Region=="Latin America & Caribbean"|  
         Region=="North America"     )


# wide_format <- Indicators2[,-c(3)] %>%
#   spread(key = "IndicatorCode",        # Name of new key column
#          value = "Value") # Name of column for values


Indicators_europe2 <- Indicators_europe %>%
        filter(IndicatorName=="GDP (current LCU)" |
                IndicatorName=="Life expectancy at birth, total (years)"| 
                IndicatorName=="International migrant stock, total"|
                IndicatorName=="Population, total"
                 )
        
# str(Indicators_europe2)
# colnames(Indicators_europe2)
# 

wide_format <- Indicators_europe2[,-c(4)] %>% 
  spread(key = "IndicatorName",        # Name of new key column
         value = "Value") # Name of column for values

names(wide_format)<-c("CountryCode","country","year","continent","gdpPercap","migrant","lifeExp","pop")


#colnames(wide_format[,c(-6)])
wide_format2 <- na.omit(wide_format[,c(-6)])

#colnames(wide_format2)
wide_format2 <- wide_format2[,c(2,4,3,5,6,7)]

#-------------------------------------------------------------------------




# Charge libraries:
library(ggplot2)
library(gganimate)

# Make a ggplot, but add frame=year: one image per year
ggplot(wide_format2, aes(gdpPercap, lifeExp, size = pop, colour = country)) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  scale_colour_manual(values = wide_format2$country) +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  facet_wrap(~continent) +
  # Here comes the gganimate specific bits
  labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
  transition_time(year) +
  ease_aes('linear')

# Save at gif:
anim_save("271-ggplot2-animated-gif-chart-with-gganimate2.gif")

```





```{r }



# Update these to plot different indicators
indicatorName <- "Life expectancy at birth, total (years)"
indicatorYear <- 1960

# setwd("E:\\Givaldo\\DATA SCIENCE\\MESTRADO CIT\\SUBJECTS\\Second Semester\\Visualizatin and Analytics\\Project 1")
# my.path <- dirname(rstudioapi::getActiveDocumentContext()$path)
# setwd(my.path)
# indicators <- read.csv("Indicators.csv")
# 
# Country <- read.csv("Country.csv")
Country_Region <-Country[,c(1,8)]

indicators2 <- merge(Indicators,Country_Region, by=c("CountryCode","CountryCode"))

colnames(indicators2)
colnames(Country_Region)

indicators <- indicators2 %>%
  filter(Region=="Europe & Central Asia")

colnames(indicators)

filtered <- indicators[indicators$IndicatorName==indicatorName & indicators$Year==indicatorYear,]
# write_csv(filtered, "filtered.csv")

correction <- c("Antigua and Barbuda"="Antigua", "Bahamas, The"="Bahamas", "Brunei Darussalam"="Brunei", "Cabo Verde"="Cape Verde", "Congo, Dem. Rep."="Democratic Republic of the Congo", "Congo, Rep."="Republic of Congo", "Cote d'Ivoire"="Ivory Coast", "Egypt, Arab Rep."="Egypt", "Faeroe Islands"="Faroe Islands", "Gambia, The"="Gambia", "Iran, Islamic Rep."="Iran", "Korea, Dem. Rep."="North Korea", "Korea, Rep."="South Korea", "Kyrgyz Republic"="Kyrgyzstan", "Lao PDR"="Laos", "Macedonia, FYR"="Macedonia", "Micronesia, Fed. Sts."="Micronesia", "Russian Federation"="Russia", "Slovak Republic"="Slovakia", "St. Lucia"="Saint Lucia", "St. Martin (French part)"="Saint Martin", "St. Vincent and the Grenadines"="Saint Vincent", "Syrian Arab Republic"="Syria", "Trinidad and Tobago"="Trinidad", "United Kingdom"="UK", "United States"="USA", "Venezuela, RB"="Venezuela", "Virgin Islands (U.S.)"="Virgin Islands", "Yemen, Rep."="Yemen")

# for (c in names((correction))) {
#   filtered[filtered$CountryName==c,"CountryName"] = correction[c]
# }

map.world <- merge(x=map_data(map="world"),
                   y=filtered[,c("CountryName","Value")],
                   by.x="region",
                   by.y="CountryName",
                   all.x=TRUE)
map.world <- map.world[order(map.world$order),]

p <- ggplot(map.world) +
  geom_map(map=map.world, aes(map_id=region, x=long, y=lat, fill=Value)) + 
  scale_fill_gradient(low = "brown3", high = "green", guide = "colourbar") +
  coord_equal() +
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.background=element_blank(),
        legend.title=element_blank(),
        legend.position="bottom") +
  ggtitle(paste0(indicatorName, " in ", indicatorYear))
ggsave("map.png", p, width=7, height=4, units="in")

p


# https://www.kaggle.com/benhamner/indicators-in-data/data
```




```{r warning=FALSE}

library(plotly)
# my.path <- dirname(rstudioapi::getActiveDocumentContext()$path)
# setwd(my.path)
# 
# Indicators <- read.csv("Indicators.csv")
# 
# Country <- read.csv("Country.csv")

Country_Region <-Country[,c(1,8)]
unique(na.omit(Country_Region$Region))

Indicators2 <- merge(Indicators,Country_Region, by=c("CountryCode","CountryCode"))
# colnames(Indicators2)
# Country$ShortName

CountryNam <- unique(Indicators2[,c(1)])
IndicatorNam <- unique(Indicators2[,c(3)])
IndicatorCod <- unique(Indicators2[,c(4)])
region <- unique(Indicators2[,c(7)])


Indicators_europe <- Indicators2 %>%
  filter(Region=="Europe & Central Asia"    )


# wide_format <- Indicators2[,-c(3)] %>%
#   spread(key = "IndicatorCode",        # Name of new key column
#          value = "Value") # Name of column for values


Indicators_europe2 <- Indicators_europe %>%
        filter(IndicatorName=="GDP per capita growth (annual %)" |
                IndicatorName=="Life expectancy at birth, total (years)"| 
                IndicatorName=="International migrant stock, total"|
                IndicatorName=="Population, total"
                 )
        
# str(Indicators_europe2)
# colnames(Indicators_europe2)
# 

wide_format <- Indicators_europe2[,-c(4)] %>% 
  spread(key = "IndicatorName",        # Name of new key column
         value = "Value") # Name of column for values

names(wide_format)<-c("CountryCode","country","year","continent","gdpPercap","migrant","lifeExp","pop")


#colnames(wide_format[,c(-6)])
wide_format2 <- na.omit(wide_format[,c(-6)])

#colnames(wide_format2)
wide_format2 <- wide_format2[,c(2,4,3,5,6,7)]

wide_format3 <- wide_format2 %>%
  filter(  country=="Switzerland"|
           country=="Germany"|
           country=="Spain"|
           country=="Finland"|
           country=="United Kingdom"|
           country=="Greece"|
           country=="Austria"|
           country=="Belgium"|
           country=="Sweden"|
             country=="Poland"|
             country=="France"|
             country=="Ireland"|
             country=="Iceland"|
             country=="Portugal"|
             country=="Italy"|
             country=="Denmark"|
           country=="Norway")

data <- data.frame(year=wide_format3$year, gdpPercap=wide_format3$gdpPercap, country=wide_format3$country)

plot_ly(data, x = ~year, y = ~gdpPercap, name = wide_format3$country, type = 'scatter', mode = 'lines', color = wide_format3$country)


```




```{r }


# my.path <- dirname(rstudioapi::getActiveDocumentContext()$path)
# setwd(my.path)

# setwd("E:\\Givaldo\\DATA SCIENCE\\MESTRADO CIT\\SUBJECTS\\Second Semester\\Visualizatin and Analytics\\Project 1")
# Indicators <- read.csv("Indicators.csv")
# Country <- read.csv("Country.csv")


# load data from Johns Hopkins github

confirmedCases= read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv')
deathCases= read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv')
recoveredCases= read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv')


# set system locale for date conversion purpose
Sys.setlocale("LC_TIME", "English")


#convert data sets into columns and remove unwanted columns

confirmedCases<-confirmedCases%>%
  select(-c(Lat,Long))%>%
  melt(id=c('Country/Region','Province/State'))

confirmedCases<-confirmedCases%>%
  group_by(`Country/Region`,variable)%>%
  summarise(Confirmed=sum(value))

deathCases<-deathCases%>%
  select(-c(Lat,Long))%>%
  melt(id=c('Country/Region','Province/State'))

deathCases<-deathCases%>%
  group_by(`Country/Region`,variable)%>%
  summarise(Deaths=sum(value))

recoveredCases<-recoveredCases%>%
  select(-c(Lat,Long))%>%
  melt(id=c('Country/Region','Province/State'))

recoveredCases<-recoveredCases%>%
  group_by(`Country/Region`,variable)%>%
  summarise(Recovered=sum(value))


# rename table columns
colnames(confirmedCases)<-c("Country","Date","Confirmed")
colnames(deathCases)<-c("Country","Date","Death")
colnames(recoveredCases)<-c("Country","Date","Recovered")

# merge all atbles together

mergedCases<-merge(confirmedCases,deathCases, by.y=c("Country","Date"))
mergedCases<-merge(mergedCases,recoveredCases, by.y=c("Country","Date"))

# convert factors to date format

mergedCases$Date<-as.Date(mergedCases$Date,"%m/%d/%y")

# summarize cases by date
df1<-mergedCases %>% group_by(Date) %>% summarise_at(c("Confirmed","Recovered","Death"),sum)

# stack columns together and add state columns to each case
df2 <- data.frame(Date=rep(df1$Date, 3), 
                  act_noact=c(df1$Confirmed, df1$Death,df1$Recovered), 
                  State=rep(c("Confirmed","Deaths", "Recovered"), each=nrow(df1)))

# retrieve last update date for title
lastDate<-max(df1$Date)

colnames(df2)#"Date" "act_noact" "State"   

# define plot object
p <- ggplot(df2, aes(x=Date, y=act_noact, group=State, color=State)) +
  geom_line() +
  geom_segment(aes(xend=max(Date), yend = act_noact), linetype=2, colour='blue') +
  geom_point(size = 3) + 
  geom_text(aes(x = max(Date)+.1, label = sprintf("%5.0f", act_noact)), hjust=-0.5) +
  transition_reveal(Date) + 
  view_follow(fixed_y = TRUE)+
  coord_cartesian(clip = 'off') + 
  xlab("Day") +
  ylab("Number of cases") + ggtitle(paste("Evolution of cases over time as of ",lastDate)) +
  enter_drift(x_mod = -1) + exit_drift(x_mod = 1) +
  theme_classic() +
  theme(legend.position = c(0.2, 0.8))+
  theme(panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  plot.margin = margin(5.5, 40, 5.5, 5.5))

p

# create animation gif file
animate(p, fps=5,renderer = gifski_renderer("virusevolution.gif"))



```




```{r }


library(plotly)
# my.path <- dirname(rstudioapi::getActiveDocumentContext()$path)
# setwd(my.path)
# 
# Indicators <- read.csv("Indicators.csv")
# 
# Country <- read.csv("Country.csv")

Country_Region <-Country[,c(1,8)]
unique(na.omit(Country_Region$Region))

Indicators2 <- merge(Indicators,Country_Region, by=c("CountryCode","CountryCode"))
# colnames(Indicators2)
# Country$ShortName

CountryNam <- unique(Indicators2[,c(1)])
IndicatorNam <- unique(Indicators2[,c(3)])
IndicatorCod <- unique(Indicators2[,c(4)])
region <- unique(Indicators2[,c(7)])


Indicators_europe <- Indicators2 %>%
  filter(Region=="Europe & Central Asia"    )


# wide_format <- Indicators2[,-c(3)] %>%
#   spread(key = "IndicatorCode",        # Name of new key column
#          value = "Value") # Name of column for values


Indicators_europe2 <- Indicators_europe %>%
        filter(IndicatorName=="GDP per capita growth (annual %)" |
                IndicatorName=="Life expectancy at birth, total (years)"| 
                IndicatorName=="International migrant stock, total"|
                IndicatorName=="Population, total"
                 )
        
# str(Indicators_europe2)
# colnames(Indicators_europe2)
# 

wide_format <- Indicators_europe2[,-c(4)] %>% 
  spread(key = "IndicatorName",        # Name of new key column
         value = "Value") # Name of column for values

names(wide_format)<-c("CountryCode","country","year","continent","gdpPercap","migrant","lifeExp","pop")


#colnames(wide_format[,c(-6)])
wide_format2 <- na.omit(wide_format[,c(-6)])

#colnames(wide_format2)
wide_format2 <- wide_format2[,c(2,4,3,5,6,7)]

wide_format3 <- wide_format2 %>%
  filter(  country=="United Kingdom"|
           country=="Ireland")

data <- data.frame(Date=wide_format3$year, gdpPercap=wide_format3$gdpPercap, country=wide_format3$country)


# retrieve last update date for title
lastDate<-max(data$Date)

# colnames(data)#"Date" "act_noact" "State"   

# define plot object
p <- ggplot(data, aes(x=Date, y=gdpPercap, group=country, color=country)) +
  geom_line() +
  geom_segment(aes(xend=max(Date), yend = gdpPercap), linetype=2, colour='blue') +
  geom_point(size = 3) + 
  geom_text(aes(x = max(Date)+.1, label = sprintf("%5.0f", gdpPercap)), hjust=-0.5) +
  transition_reveal(Date) + 
  view_follow(fixed_y = TRUE)+
  coord_cartesian(clip = 'off') + 
  xlab("Year") +
  ylab("gdpPercap") + ggtitle(paste("Evolution of gdpPercap ",lastDate)) +
  enter_drift(x_mod = -1) + exit_drift(x_mod = 1) +
  theme_classic() +
  theme(legend.position = c(0.2, 0.8))+
  theme(panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black"),
  plot.margin = margin(10.5, 40, 10.5, 10.5))

# create animation gif file
animate(p, fps=5,renderer = gifski_renderer("virusevolution.gif"))

p

```







